[tool.flake8]
select = ["T201", "T203", "E800"]

[tool.pylint.basic]
no-docstring-rgx = "^_"

[tool.pylint."messages control"]
disable = "all"
enable = [
    "unused-import",
    "wildcard-import",
    "unused-argument",
    "dangerous-default-value",
    "unused-variable",
    "undefined-variable",
    "fixme",
    "missing-function-docstring",
    "missing-class-docstring",
    "inconsistent-return-statements",
    "access-member-before-definition",
    "attribute-defined-outside-init",
    "function-redefined",
    "return-outside-function",
    "yield-outside-function",
]

[tool.pylint.variables]
ignored-argument-names = "_.*|^ignored_|^unused_"
