name: MD to PDF
# only run if .md updated
on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**.md'
    types:
      - closed
jobs:
  makepdfs:
    if: ${{ github.repository != 'Deloitte/SFL-Template' && github.event.pull_request.merged == 'true' }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Install Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.8.3'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install -r .github/default/md_to_pdf_converion/md_to_pdf_requirements.txt
    - name: Convert Notebooks
      run: python .github/default/convert_md_to_pdf.py 
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3.10.0
      with:
        commit-message: PR with converted to PDF
        committer: AutoCommit <example@users.noreply.github.com>
        title: File conversions MD_to_PDF
        body: This is an auto-generated PR
        labels: pdfs, automated pr
        branch: ${{ format('md-to-pdf_{0}', github.head_ref) }}
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.cpr.outputs.pull-request-number }}
        method: squash