name: create-pull-request workflow
on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/**
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v3
      - name: Find Repositories with .github folder
        id: find-repos
        run: |
          # List of repositories with Deloitte org and label sfl
          repos=$(gh repo list Deloitte --limit 1000 --topic sfl | awk -F'/' '{print $2}' | awk '{print $1}')
          
          # Filter repositories that have a .github folder
          repos_with_dotgithub=()
          for repo in $repos; do
            if [ "$repo" != "SFL-Template" ]; then
              echo "Processing repository: $repo"
              response=$(gh api "repos/Deloitte/$repo/contents" -H "Accept: application/vnd.github.v3+json" -i)
              status_code=$?
              
              # Check if the response contains the .github folder
              if echo "$response" | grep -q '\"name\":\".github\"'; then
                repos_with_dotgithub+=("$repo")
              else
                echo "Warning: .github folder not found in repository $repo"
              fi
            fi
          done
          # echo "${repos_with_dotgithub[*]}" to view all repos with .github
          echo "::set-output name=repos::${repos_with_dotgithub[*]}"
          
      - name: Create Pull Requests
        env:
          REPOS_WITH_DOTGITHUB: ${{ steps.find-repos.outputs.repos }}
        run: |
          # Split the REPOS_WITH_DOTGITHUB into an array
          IFS=' ' read -ra repos_with_dotgithub <<< "$REPOS_WITH_DOTGITHUB"

          for repo in "${repos_with_dotgithub[@]}"; do
          
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"

            sleep 2

            git clone https://"$GH_TOKEN"@github.com/Deloitte/"$repo".git temp-repo
            echo "Cloning repository: $repo"

            cd temp-repo

            branch_name="update-github-folder-$(date +'%Y%m%d%H%M%S')"

            git checkout -b "$branch_name"
            echo "Created new branch: $branch_name"

            rsync -r ../.github/* .github/
            rm .github/workflows/pr_all_github_repos.yml

            if [[ -z $(git status --porcelain) ]]; then
              echo "No changes to commit"
            else
              git add -f .github
              git commit -m "Update .github folder"
              echo "Committed changes"

              sleep 2

              git push origin "$branch_name"
              echo "Pushed changes to remote"

              sleep 60

              gh pr create --title "[GitHub Workflows Version Update] Update .github folder" --body "This PR is auto-generated by [pr_all_github_repos](https://github.com/Deloitte/SFL-Template)."
            fi
            
            cd ..
            rm -rf temp-repo
          done
