import React from "react";
import { Typography } from "@mui/material";
import SentimentFilter from "./Filters/SentimentFilter";
import ToxicityFilter from "./Filters/ToxicityFilter";
import BanSubstringsFilter from "./Filters/BanSubstringsFilter";
import BanTopicsFilter from "./Filters/BanTopicsFilter";
import CodeFilter from "./Filters/CodeFilter";
import LanguageFilter from "./Filters/LanguageFilter";
import RegexFilter from "./Filters/RegexFilter";
import BiasFilter from "./Filters/BiasFilter";
import DeanonymizeFilter from "./Filters/DeanonymizeFilter";
import FactualConsistencyFilter from "./Filters/FactualConsistencyFilter";
import ReadingTimeFilter from "./Filters/ReadingTimeFilter";
import RelevanceFilter from "./Filters/RelevanceFilter";
import LanguageSameFilter from "./Filters/LanguageSameFilter";
import MaliciousURLsFilter from "./Filters/MaliciousURLsFilter";
import NoRefusalFilter from "./Filters/NoRefusalFilter";
import URLReachabilityFilter from "./Filters/URLReachabilityFilter";
import SensitiveFilter from "./Filters/SensitiveFilter";

export default function OutputScanners(props) {
    const {CurrentPage} = props;

    return (
        <div>
            <Typography variant="h4">Output Scanners</Typography>
            <Typography variant="h6" color="#87BC1F">Privacy</Typography>
            <DeanonymizeFilter filterName="Deanonymize" helperText="This scanner helps put back real values in the model's output by replacing placeholders."/>
            <SensitiveFilter filterName="Sensitive" helperText="The Sensitive Scanner serves as your digital vanguard, ensuring that the language model's output is purged of Personally Identifiable Information (PII) and other sensitive data, safeguarding user interactions."/>
            <Typography variant="h6" color="#87BC1F">Fair & Impartial</Typography>
            <SentimentFilter CurrentPage={CurrentPage} filterName="Sentiment" helperText="The Sentiment Scanner is designed to scan and assess the sentiment of generated outputs. It leverages the SentimentIntensityAnalyzer from the NLTK (Natural Language Toolkit) library to accomplish this."/>
            <BiasFilter filterName="Bias" helperText="This scanner is designed to inspect the outputs generated by Language Learning Models (LLMs) to detect and evaluate potential biases. Its primary function is to ensure that LLM outputs remain neutral and don't exhibit unwanted or predefined biases."/>
            <Typography variant="h6" color="#87BC1F">Responsible</Typography>
            <BanSubstringsFilter CurrentPage={CurrentPage} filterName="Ban Substrings" helperText="BanSubstrings scanner provides a safeguard mechanism to prevent undesired substrings from appearing in the language model's outputs."/>
            <BanTopicsFilter CurrentPage={CurrentPage} filterName="Ban Topics" helperText="This scanner is designed to detect outputs that touch upon topics that are considered sensitive using Zero-Shot classifier."/>
            <ToxicityFilter CurrentPage={CurrentPage} filterName="Toxicity" helperText="It is designed to assess the toxicity level of the content generated by language models, acting as a safeguard against potentially harmful or offensive output."/>
            <Typography variant="h6" color="#87BC1F">Robust & Reliable</Typography>
            <FactualConsistencyFilter filterName="Factual Consistency" helperText="This scanner is designed to assess if the given content contradicts or refutes a certain statement or prompt. It acts as a tool for ensuring the consistency and correctness of language model outputs, especially in contexts where logical contradictions can be problematic."/>
            <RelevanceFilter filterName="Relevance" helperText="This scanner ensures that output remains relevant and aligned with the given input prompt."/>
            <ReadingTimeFilter filterName="Reading Time" helperText="This scanner estimates and manages the reading time of text content. It is particularly useful for applications where content length and reading time need to be controlled, such as in educational materials or time-sensitive reading platforms."/>
            <URLReachabilityFilter filterName="URL Reachability" helperText="This scanner identifies URLs in the text and checks them for accessibility, ensuring that all URLs are reachable and not broken. Uses the following HTTP status codes: 200, 201, 202, 301, 302"/>
            <Typography variant="h6" color="#87BC1F">Safe & Secure</Typography>
            <CodeFilter CurrentPage={CurrentPage} filterName="Code" helperText="This scanner can be particularly useful in applications that need to accept only code snippets in specific languages."/>
            <LanguageFilter CurrentPage={CurrentPage} filterName="Language" helperText="This scanner identifies and assesses the authenticity of the language used in outputs."/>
            <LanguageSameFilter filterName="Language Same" helperText="This scanner evaluates and checks if the prompt and output are in the same language."/>
            <MaliciousURLsFilter filterName="Malicious URLs" helperText="This scanner detects URLs in the output and analyzes them for harmfulness, such as detecting phishing websites."/>
            <NoRefusalFilter filterName="No Refusal" helperText="It is specifically designed to detect refusals in the output of language models. It can be especially useful to detect when someone is trying to force the model to produce a harmful output."/>
            <RegexFilter CurrentPage={CurrentPage} filterName="Regex" helperText={"This scanner is designed to sanitize outputs based on predefined regular expression patterns. It offers flexibility in defining patterns to identify and process desirable or undesirable content within the outputs."}/>
        </div>
    );
}



// curl https://advisorygenai.openai.azure.com/openai/deployments/advisory-genai-gpt-4/completions?api-version=2023-05-15 -H "Content-Type: application/json" -H "api-key: 4744cdfb0fd340788c775a7b4f46951e" -d "{\"prompt\": \"Once upon a time\"}"

// {"content": "Given the personal profile of Johnathan Edward Doe, please summarize the following resume: Profile: Full Name: Johnathan Edward Doe. Date of Birth: April 12, 1990. Address: 123 Elm Street, Springfield, IL, 62701. Email: [john.doe@example.com](mailto:john.doe@example.com). Phone Number: [(123) 456-7890](tel:1234567890). Educational Background: Springfield High School, Graduated in 2008; Springfield University, B.Sc. Computer Science, Graduated in 2012. Employment: ABC Tech Solutions, Software Engineer, 2012-2015; XYZ Global Systems, Senior Software Developer, 2015-2021."}